development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: fishing_diary_development
  pool:     5
  username: koza
  password: koza
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: fishing_diary_test
  pool:     5
  username: koza
  password: koza
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: fishing_diary_production
  pool:     5
  username: koza
  password: koza
  template: template0
